### ISSUE TITLE
This tool does not work with unity 2022.3.6f1.

### ISSUE THREAD

**Issue by Mizu-Aya-SL** [Swagguy47/VRChat-Titanfall-Unity-Tools#24]
This tool does not work with unity 2022.3.6f1.
As soon as I import the plugin it reports an error and won't work
![{A818EF8A-6944-4b23-ACD3-45FCD9302E35}](https://github.com/Swagguy47/VRChat-Titanfall-Unity-Tools/assets/57021305/a27a8cd3-3319-4aac-b0b3-9007133628c5)

**Comment by Swagguy47** [comment]
Thanks for reporting!
This issue has been resolved in v.2.7
